package com.example.asm.modify;

import com.example.Const;
import com.example.Util;
import com.example.java_demo.IShowable;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;

/**
 * 修改java 字节码版本
 */
public class ModifyJavaVersion {
    public static void main(String[] args) throws Exception {
        ClassReader cr = new ClassReader(Const.CLASS_HELLO);
        ClassWriter cw = new ClassWriter(0);
        ClassVisitor adapter = new ClassVisitor(Opcodes.ASM5, cw) {
            @Override
            public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
                // modify class version and name
                cv.visit(Opcodes.V1_5, access, "Hello3", signature, superName, interfaces);
            }
        };
        cr.accept(adapter, 0);

        Util.saveClass(cw, "Hello3.class");
        // compare Hello3.class to Hello.class by text, generate through hexdump, or other hex comparable tool.

        // define class from generated byte[]
        Class aClass = Util.defineClass("Hello3", cw.toByteArray());
        // Hello3 implements IShowable, cast to it.
        IShowable iShow = (IShowable) aClass.newInstance();
        // using interface's method invocation instead of reflection
        iShow.show();// Hello3:show()
    }

}
